/* Copyright (C) Siqi.Wu - All Rights Reserved
* Written by Siqi.Wu<lion547016@gmail.com>, September 2019
*/

#pragma once

#include "CoreMinimal.h"

#include "EC2InstanceType.generated.h"

UENUM(BlueprintType)
enum class EEC2InstanceType : uint8 {
    NOT_SET        UMETA(DisplayName = "not set"),
    t2_micro        UMETA(DisplayName = "t2 micro"),
    t2_small        UMETA(DisplayName = "t2 small"),
    t2_medium        UMETA(DisplayName = "t2 medium"),
    t2_large        UMETA(DisplayName = "t2 large"),
    c3_large        UMETA(DisplayName = "c3 large"),
    c3_xlarge        UMETA(DisplayName = "c3 xlarge"),
    c3_2xlarge        UMETA(DisplayName = "c3 2xlarge"),
    c3_4xlarge        UMETA(DisplayName = "c3 4xlarge"),
    c3_8xlarge        UMETA(DisplayName = "c3 8xlarge"),
    c4_large        UMETA(DisplayName = "c4 large"),
    c4_xlarge        UMETA(DisplayName = "c4 xlarge"),
    c4_2xlarge        UMETA(DisplayName = "c4 2xlarge"),
    c4_4xlarge        UMETA(DisplayName = "c4 4xlarge"),
    c4_8xlarge        UMETA(DisplayName = "c4 8xlarge"),
    c5_large        UMETA(DisplayName = "c5 large"),
    c5_xlarge        UMETA(DisplayName = "c5 xlarge"),
    c5_2xlarge        UMETA(DisplayName = "c5 2xlarge"),
    c5_4xlarge        UMETA(DisplayName = "c5 4xlarge"),
    c5_9xlarge        UMETA(DisplayName = "c5 9xlarge"),
    c5_12xlarge        UMETA(DisplayName = "c5 12xlarge"),
    c5_18xlarge        UMETA(DisplayName = "c5 18xlarge"),
    c5_24xlarge        UMETA(DisplayName = "c5 24xlarge"),
    c5a_large        UMETA(DisplayName = "c5a large"),
    c5a_xlarge        UMETA(DisplayName = "c5a xlarge"),
    c5a_2xlarge        UMETA(DisplayName = "c5a 2xlarge"),
    c5a_4xlarge        UMETA(DisplayName = "c5a 4xlarge"),
    c5a_8xlarge        UMETA(DisplayName = "c5a 8xlarge"),
    c5a_12xlarge        UMETA(DisplayName = "c5a 12xlarge"),
    c5a_16xlarge        UMETA(DisplayName = "c5a 16xlarge"),
    c5a_24xlarge        UMETA(DisplayName = "c5a 24xlarge"),
    r3_large        UMETA(DisplayName = "r3 large"),
    r3_xlarge        UMETA(DisplayName = "r3 xlarge"),
    r3_2xlarge        UMETA(DisplayName = "r3 2xlarge"),
    r3_4xlarge        UMETA(DisplayName = "r3 4xlarge"),
    r3_8xlarge        UMETA(DisplayName = "r3 8xlarge"),
    r4_large        UMETA(DisplayName = "r4 large"),
    r4_xlarge        UMETA(DisplayName = "r4 xlarge"),
    r4_2xlarge        UMETA(DisplayName = "r4 2xlarge"),
    r4_4xlarge        UMETA(DisplayName = "r4 4xlarge"),
    r4_8xlarge        UMETA(DisplayName = "r4 8xlarge"),
    r4_16xlarge        UMETA(DisplayName = "r4 16xlarge"),
    r5_large        UMETA(DisplayName = "r5 large"),
    r5_xlarge        UMETA(DisplayName = "r5 xlarge"),
    r5_2xlarge        UMETA(DisplayName = "r5 2xlarge"),
    r5_4xlarge        UMETA(DisplayName = "r5 4xlarge"),
    r5_8xlarge        UMETA(DisplayName = "r5 8xlarge"),
    r5_12xlarge        UMETA(DisplayName = "r5 12xlarge"),
    r5_16xlarge        UMETA(DisplayName = "r5 16xlarge"),
    r5_24xlarge        UMETA(DisplayName = "r5 24xlarge"),
    r5a_large        UMETA(DisplayName = "r5a large"),
    r5a_xlarge        UMETA(DisplayName = "r5a xlarge"),
    r5a_2xlarge        UMETA(DisplayName = "r5a 2xlarge"),
    r5a_4xlarge        UMETA(DisplayName = "r5a 4xlarge"),
    r5a_8xlarge        UMETA(DisplayName = "r5a 8xlarge"),
    r5a_12xlarge        UMETA(DisplayName = "r5a 12xlarge"),
    r5a_16xlarge        UMETA(DisplayName = "r5a 16xlarge"),
    r5a_24xlarge        UMETA(DisplayName = "r5a 24xlarge"),
    m3_medium        UMETA(DisplayName = "m3 medium"),
    m3_large        UMETA(DisplayName = "m3 large"),
    m3_xlarge        UMETA(DisplayName = "m3 xlarge"),
    m3_2xlarge        UMETA(DisplayName = "m3 2xlarge"),
    m4_large        UMETA(DisplayName = "m4 large"),
    m4_xlarge        UMETA(DisplayName = "m4 xlarge"),
    m4_2xlarge        UMETA(DisplayName = "m4 2xlarge"),
    m4_4xlarge        UMETA(DisplayName = "m4 4xlarge"),
    m4_10xlarge        UMETA(DisplayName = "m4 10xlarge"),
    m5_large        UMETA(DisplayName = "m5 large"),
    m5_xlarge        UMETA(DisplayName = "m5 xlarge"),
    m5_2xlarge        UMETA(DisplayName = "m5 2xlarge"),
    m5_4xlarge        UMETA(DisplayName = "m5 4xlarge"),
    m5_8xlarge        UMETA(DisplayName = "m5 8xlarge"),
    m5_12xlarge        UMETA(DisplayName = "m5 12xlarge"),
    m5_16xlarge        UMETA(DisplayName = "m5 16xlarge"),
    m5_24xlarge        UMETA(DisplayName = "m5 24xlarge"),
    m5a_large        UMETA(DisplayName = "m5a large"),
    m5a_xlarge        UMETA(DisplayName = "m5a xlarge"),
    m5a_2xlarge        UMETA(DisplayName = "m5a 2xlarge"),
    m5a_4xlarge        UMETA(DisplayName = "m5a 4xlarge"),
    m5a_8xlarge        UMETA(DisplayName = "m5a 8xlarge"),
    m5a_12xlarge        UMETA(DisplayName = "m5a 12xlarge"),
    m5a_16xlarge        UMETA(DisplayName = "m5a 16xlarge"),
    m5a_24xlarge        UMETA(DisplayName = "m5a 24xlarge"),
};
